insert into courses values(default,"Angular");
insert into courses values(default,"TypeScript");
insert into courses values(default,"JavaScript");
insert into courses values(default,"Node");
insert into courses values(default,"Express");
insert into courses values(default,"jQuery");
insert into courses values(default,"Spring");
insert into courses values(default,"SpringBoot");
insert into courses values(default,"Hibernate");
insert into courses values(default,"Spring Data JPA");
