INSERT INTO state VALUES
(DEFAULT, "Andaman and Nicobar Islands"),
(DEFAULT, "Andhra Pradesh"),
(DEFAULT, "Arunachal Pradesh"),
(DEFAULT, "Assam"),
(DEFAULT, "Bihar"),
(DEFAULT, "Chandigarh"),
(DEFAULT, "Chhattisgarh"),
(DEFAULT, "Dadra and Nagar Haveli and Daman and Diu"),
(DEFAULT, "Delhi"),
(DEFAULT, "Goa"),
(DEFAULT, "Gujarat"),
(DEFAULT, "Haryana"),
(DEFAULT, "Himachal Pradesh"),
(DEFAULT, "Jammu and Kashmir"),
(DEFAULT, "Jharkhand"),
(DEFAULT, "Karnataka"),
(DEFAULT, "Kerala"),
(DEFAULT, "Ladakh"),
(DEFAULT, "Lakshadweep"),
(DEFAULT, "Madhya Pradesh"),
(DEFAULT, "Maharashtra"),
(DEFAULT, "Manipur"),
(DEFAULT, "Meghalaya"),
(DEFAULT, "Mizoram"),
(DEFAULT, "Nagaland"),
(DEFAULT, "Odisha"),
(DEFAULT, "Puducherry"),
(DEFAULT, "Punjab"),
(DEFAULT, "Rajasthan"),
(DEFAULT, "Sikkim"),
(DEFAULT, "Tamil Nadu"),
(DEFAULT, "Telangana"),
(DEFAULT, "Tripura"),
(DEFAULT, "Uttar Pradesh"),
(DEFAULT, "Uttarakhand"),
(DEFAULT, "West Bengal");


INSERT INTO district VALUES

(DEFAULT, "Nicobars", 1),
(DEFAULT, "North and Middle Andaman", 1),
(DEFAULT, "South Andaman", 1),

(DEFAULT, "Anantapur", 2),
(DEFAULT, "Chittoor", 2),
(DEFAULT, "East Godavari", 2),
(DEFAULT, "Guntur", 2),
(DEFAULT, "Krishna", 2),
(DEFAULT, "Kurnool", 2),
(DEFAULT, "Prakasam", 2),
(DEFAULT, "S.P.S. Nellore", 2),
(DEFAULT, "Srikakulam", 2),
(DEFAULT, "Visakhapatnam", 2),
(DEFAULT, "Vizianagaram", 2),
(DEFAULT, "West Godavari", 2),

(DEFAULT, "Anjaw", 3),
(DEFAULT, "Changlang", 3),
(DEFAULT, "East Kameng", 3),
(DEFAULT, "East Siang", 3),
(DEFAULT, "Kamle", 3),
(DEFAULT, "Kra Daadi", 3),
(DEFAULT, "Kurung Kumey", 3),
(DEFAULT, "Lepa Rada", 3),
(DEFAULT, "Lohit", 3),
(DEFAULT, "Longding", 3),
(DEFAULT, "Lower Dibang Valley", 3),
(DEFAULT, "Lower Siang", 3),
(DEFAULT, "Lower Subansiri", 3),
(DEFAULT, "Namsai", 3),
(DEFAULT, "Pakke Kessang", 3),
(DEFAULT, "Papum Pare", 3),
(DEFAULT, "Shi Yomi", 3),
(DEFAULT, "Siang", 3),
(DEFAULT, "Tawang", 3),
(DEFAULT, "Tirap", 3),
(DEFAULT, "Upper Dibang Valley", 3),
(DEFAULT, "Upper Siang", 3),
(DEFAULT, "Upper Subansiri", 3),
(DEFAULT, "West Kameng", 3),
(DEFAULT, "West Siang", 3),

(DEFAULT, "Baksa", 4),
(DEFAULT, "Barpeta", 4),
(DEFAULT, "Biswanath", 4),
(DEFAULT, "Bongaigaon", 4),
(DEFAULT, "Cachar", 4),
(DEFAULT, "Charaideo", 4),
(DEFAULT, "Chirang", 4),
(DEFAULT, "Darrang", 4),
(DEFAULT, "Dhemaji", 4),
(DEFAULT, "Dhubri", 4),
(DEFAULT, "Dibrugarh", 4),
(DEFAULT, "Dima Hasao", 4),
(DEFAULT, "Goalpara", 4),
(DEFAULT, "Golaghat", 4),
(DEFAULT, "Hailakandi", 4),
(DEFAULT, "Kamrup", 4),
(DEFAULT, "Kamrup Metropolitan", 4),
(DEFAULT, "Karbi Anglong", 4),
(DEFAULT, "Karimganj", 4),
(DEFAULT, "Kokrajhar", 4),
(DEFAULT, "Lakhimpur", 4),
(DEFAULT, "Majuli", 4),
(DEFAULT, "Morigaon", 4),
(DEFAULT, "Nagaon", 4),
(DEFAULT, "Nalbari", 4),
(DEFAULT, "Sivasagar", 4),
(DEFAULT, "South Salmara Mankachar", 4),
(DEFAULT, "Tinsukia", 4),
(DEFAULT, "Udalguri", 4),
(DEFAULT, "West Karbi Anglong", 4),

(DEFAULT, "Araria", 5),
(DEFAULT, "Arwal", 5),
(DEFAULT, "Aurangabad", 5),
(DEFAULT, "Banka", 5),
(DEFAULT, "Begusarai", 5),
(DEFAULT, "Bhagalpur", 5),
(DEFAULT, "Bhojpur", 5),
(DEFAULT, "Buxar", 5),
(DEFAULT, "Darbhanga", 5),
(DEFAULT, "East Champaran", 5),
(DEFAULT, "Gaya", 5),
(DEFAULT, "Gopalganj", 5),
(DEFAULT, "Jamui", 5),
(DEFAULT, "Jehanabad", 5),
(DEFAULT, "Kaimur", 5),
(DEFAULT, "Katihar", 5),
(DEFAULT, "Khagaria", 5),
(DEFAULT, "Kishanganj", 5),
(DEFAULT, "Lakhisarai", 5),
(DEFAULT, "Madhepura", 5),
(DEFAULT, "Madhubani", 5),
(DEFAULT, "Munger", 5),
(DEFAULT, "Muzaffarpur", 5),
(DEFAULT, "Nalanda", 5),
(DEFAULT, "Nawada", 5),
(DEFAULT, "Patna", 5),
(DEFAULT, "Purnia", 5),
(DEFAULT, "Rohtas", 5),
(DEFAULT, "Saharsa", 5),
(DEFAULT, "Samastipur", 5),
(DEFAULT, "Saran", 5),
(DEFAULT, "Sheikhpura", 5),
(DEFAULT, "Sheohar", 5),
(DEFAULT, "Sitamarhi", 5),
(DEFAULT, "Siwan", 5),
(DEFAULT, "Supaul", 5),
(DEFAULT, "Vaishali", 5),
(DEFAULT, "West Champaran", 5),

(DEFAULT, "Chandigarh", 6),

(DEFAULT, "Balod", 7),
(DEFAULT, "Baloda Bazar", 7),
(DEFAULT, "Balrampur", 7),
(DEFAULT, "Bametara", 7),
(DEFAULT, "Bastar", 7),
(DEFAULT, "Bijapur", 7),
(DEFAULT, "Bilaspur", 7),
(DEFAULT, "Dakshin Bastar Dantewada", 7),
(DEFAULT, "Dhamtari", 7),
(DEFAULT, "Durg", 7),
(DEFAULT, "Gariaband", 7),
(DEFAULT, "Janjgir Champa", 7),
(DEFAULT, "Jashpur", 7),
(DEFAULT, "Kabeerdham", 7),
(DEFAULT, "Kondagaon", 7),
(DEFAULT, "Korba", 7),
(DEFAULT, "Koriya", 7),
(DEFAULT, "Mahasamund", 7),
(DEFAULT, "Mungeli", 7),
(DEFAULT, "Narayanpur", 7),
(DEFAULT, "Raigarh", 7),
(DEFAULT, "Raipur", 7),
(DEFAULT, "Rajnandgaon", 7),
(DEFAULT, "Sukma", 7),
(DEFAULT, "Surajpur", 7),
(DEFAULT, "Surguja", 7),
(DEFAULT, "Uttar Bastar Kanker", 7),
(DEFAULT, "Gaurela Pendra Marwahi", 7),

(DEFAULT, "Dadra and Nagar Haveli", 8),
(DEFAULT, "Daman", 8),
(DEFAULT, "Diu", 8),

(DEFAULT, "Central Delhi", 9),
(DEFAULT, "East Delhi", 9),
(DEFAULT, "New Delhi", 9),
(DEFAULT, "North Delhi", 9),
(DEFAULT, "North East Delhi", 9),
(DEFAULT, "North West Delhi", 9),
(DEFAULT, "Shahdara", 9),
(DEFAULT, "South Delhi", 9),
(DEFAULT, "South East Delhi", 9),
(DEFAULT, "South West Delhi", 9),
(DEFAULT, "West Delhi", 9),

(DEFAULT, "North Goa", 10),
(DEFAULT, "South Goa", 10),

(DEFAULT, "Ahmedabad", 11),
(DEFAULT, "Amreli", 11),
(DEFAULT, "Anand", 11),
(DEFAULT, "Aravalli", 11),
(DEFAULT, "Banaskantha", 11),
(DEFAULT, "Bharuch", 11),
(DEFAULT, "Bhavnagar", 11),
(DEFAULT, "Botad", 11),
(DEFAULT, "Chhota Udaipur", 11),
(DEFAULT, "Dahod", 11),
(DEFAULT, "Dang", 11),
(DEFAULT, "Devbhumi Dwarka", 11),
(DEFAULT, "Gandhinagar", 11),
(DEFAULT, "Gir Somnath", 11),
(DEFAULT, "Jamnagar", 11),
(DEFAULT, "Junagadh", 11),
(DEFAULT, "Kheda", 11),
(DEFAULT, "Kutch", 11),
(DEFAULT, "Mahisagar", 11),
(DEFAULT, "Mehsana", 11),
(DEFAULT, "Morbi", 11),
(DEFAULT, "Narmada", 11),
(DEFAULT, "Navsari", 11),
(DEFAULT, "Panchmahal", 11),
(DEFAULT, "Patan", 11),
(DEFAULT, "Porbandar", 11),
(DEFAULT, "Rajkot", 11),
(DEFAULT, "Sabarkantha", 11),
(DEFAULT, "Surat", 11),
(DEFAULT, "Surendranagar", 11),
(DEFAULT, "Tapi", 11),
(DEFAULT, "Vadodara", 11),
(DEFAULT, "Valsad", 11),

(DEFAULT, "Ambala", 12),
(DEFAULT, "Bhiwani", 12),
(DEFAULT, "Charkhi Dadri", 12),
(DEFAULT, "Faridabad", 12),
(DEFAULT, "Fatehabad", 12),
(DEFAULT, "Gurugram", 12),
(DEFAULT, "Hisar", 12),
(DEFAULT, "Jhajjar", 12),
(DEFAULT, "Jind", 12),
(DEFAULT, "Kaithal", 12),
(DEFAULT, "Karnal", 12),
(DEFAULT, "Kurukshetra", 12),
(DEFAULT, "Mahendragarh", 12),
(DEFAULT, "Nuh", 12),
(DEFAULT, "Palwal", 12),
(DEFAULT, "Panchkula", 12),
(DEFAULT, "Panipat", 12),
(DEFAULT, "Rewari", 12),
(DEFAULT, "Rohtak", 12),
(DEFAULT, "Sirsa", 12),
(DEFAULT, "Sonipat", 12),
(DEFAULT, "Yamunanagar", 12),

(DEFAULT, "Bilaspur", 13),
(DEFAULT, "Chamba", 13),
(DEFAULT, "Hamirpur", 13),
(DEFAULT, "Kangra", 13),
(DEFAULT, "Kinnaur", 13),
(DEFAULT, "Kullu", 13),
(DEFAULT, "Lahaul and Spiti", 13),
(DEFAULT, "Mandi", 13),
(DEFAULT, "Shimla", 13),
(DEFAULT, "Sirmaur", 13),
(DEFAULT, "Solan", 13),
(DEFAULT, "Una", 13),

(DEFAULT, "Anantnag", 14),
(DEFAULT, "Bandipora", 14),
(DEFAULT, "Baramulla", 14),
(DEFAULT, "Budgam", 14),
(DEFAULT, "Doda", 14),
(DEFAULT, "Ganderbal", 14),
(DEFAULT, "Jammu", 14),
(DEFAULT, "Kathua", 14),
(DEFAULT, "Kishtwar", 14),
(DEFAULT, "Kulgam", 14),
(DEFAULT, "Kupwara", 14),
(DEFAULT, "Mirpur", 14),
(DEFAULT, "Muzaffarabad", 14),
(DEFAULT, "Pulwama", 14),
(DEFAULT, "Punch", 14),
(DEFAULT, "Rajouri", 14),
(DEFAULT, "Ramban", 14),
(DEFAULT, "Reasi", 14),
(DEFAULT, "Samba", 14),
(DEFAULT, "Shopiyan", 14),
(DEFAULT, "Srinagar", 14),
(DEFAULT, "Udhampur", 14),

(DEFAULT, "Bokaro", 15),
(DEFAULT, "Chatra", 15),
(DEFAULT, "Deoghar", 15),
(DEFAULT, "Dhanbad", 15),
(DEFAULT, "Dumka", 15),
(DEFAULT, "East Singhbhum", 15),
(DEFAULT, "Garhwa", 15),
(DEFAULT, "Giridih", 15),
(DEFAULT, "Godda", 15),
(DEFAULT, "Gumla", 15),
(DEFAULT, "Hazaribagh", 15),
(DEFAULT, "Jamtara", 15),
(DEFAULT, "Khunti", 15),
(DEFAULT, "Koderma", 15),
(DEFAULT, "Latehar", 15),
(DEFAULT, "Lohardaga", 15),
(DEFAULT, "Pakur", 15),
(DEFAULT, "Palamu", 15),
(DEFAULT, "Ramgarh", 15),
(DEFAULT, "Ranchi", 15),
(DEFAULT, "Sahibganj", 15),
(DEFAULT, "Saraikela-Kharsawan", 15),
(DEFAULT, "Simdega", 15),
(DEFAULT, "West Singhbhum", 15),

(DEFAULT, "Bagalkote", 16),
(DEFAULT, "Ballari", 16),
(DEFAULT, "Belagavi", 16),
(DEFAULT, "Bengaluru Rural", 16),
(DEFAULT, "Bengaluru Urban", 16),
(DEFAULT, "Bidar", 16),
(DEFAULT, "Chamarajanagara", 16),
(DEFAULT, "Chikkaballapura", 16),
(DEFAULT, "Chikkamagaluru", 16),
(DEFAULT, "Chitradurga", 16),
(DEFAULT, "Dakshina Kannada", 16),
(DEFAULT, "Davanagere", 16),
(DEFAULT, "Dharwad", 16),
(DEFAULT, "Gadag", 16),
(DEFAULT, "Hassan", 16),
(DEFAULT, "Haveri", 16),
(DEFAULT, "Kalaburagi", 16),
(DEFAULT, "Kodagu", 16),
(DEFAULT, "Kolar", 16),
(DEFAULT, "Koppal", 16),
(DEFAULT, "Mandya", 16),
(DEFAULT, "Mysuru", 16),
(DEFAULT, "Raichur", 16),
(DEFAULT, "Ramanagara", 16),
(DEFAULT, "Shivamogga", 16),
(DEFAULT, "Tumakuru", 16),
(DEFAULT, "Udupi", 16),
(DEFAULT, "Uttara Kannada", 16),
(DEFAULT, "Vijayapura", 16),
(DEFAULT, "Yadgir", 16),

(DEFAULT, "Alappuzha", 17),
(DEFAULT, "Ernakulam", 17),
(DEFAULT, "Idukki", 17),
(DEFAULT, "Kannur", 17),
(DEFAULT, "Kasaragod", 17),
(DEFAULT, "Kollam", 17),
(DEFAULT, "Kottayam", 17),
(DEFAULT, "Kozhikode", 17),
(DEFAULT, "Malappuram", 17),
(DEFAULT, "Palakkad", 17),
(DEFAULT, "Pathanamthitta", 17),
(DEFAULT, "Thiruvananthapuram", 17),
(DEFAULT, "Thrissur", 17),
(DEFAULT, "Wayanad", 17),

(DEFAULT, "Kargil", 18),
(DEFAULT, "Leh", 18),

(DEFAULT, "Lakshadweep", 19),

(DEFAULT, "Agar Malwa", 20),
(DEFAULT, "Alirajpur", 20),
(DEFAULT, "Anuppur", 20),
(DEFAULT, "Ashoknagar", 20),
(DEFAULT, "Balaghat", 20),
(DEFAULT, "Barwani", 20),
(DEFAULT, "Betul", 20),
(DEFAULT, "Bhind", 20),
(DEFAULT, "Bhopal", 20),
(DEFAULT, "Burhanpur", 20),
(DEFAULT, "Chhatarpur", 20),
(DEFAULT, "Chhindwara", 20),
(DEFAULT, "Damoh", 20),
(DEFAULT, "Datia", 20),
(DEFAULT, "Dewas", 20),
(DEFAULT, "Dhar", 20),
(DEFAULT, "Dindori", 20),
(DEFAULT, "Guna", 20),
(DEFAULT, "Gwalior", 20),
(DEFAULT, "Harda", 20),
(DEFAULT, "Hoshangabad", 20),
(DEFAULT, "Indore", 20),
(DEFAULT, "Jabalpur", 20),
(DEFAULT, "Jhabua", 20),
(DEFAULT, "Katni", 20),
(DEFAULT, "Khandwa", 20),
(DEFAULT, "Khargone", 20),
(DEFAULT, "Mandla", 20),
(DEFAULT, "Mandsaur", 20),
(DEFAULT, "Morena", 20),
(DEFAULT, "Narsinghpur", 20),
(DEFAULT, "Neemuch", 20),
(DEFAULT, "Niwari", 20),
(DEFAULT, "Panna", 20),
(DEFAULT, "Raisen", 20),
(DEFAULT, "Rajgarh", 20),
(DEFAULT, "Ratlam", 20),
(DEFAULT, "Rewa", 20),
(DEFAULT, "Sagar", 20),
(DEFAULT, "Satna", 20),
(DEFAULT, "Sehore", 20),
(DEFAULT, "Seoni", 20),
(DEFAULT, "Shahdol", 20),
(DEFAULT, "Shajapur", 20),
(DEFAULT, "Sheopur", 20),
(DEFAULT, "Shivpuri", 20),
(DEFAULT, "Sidhi", 20),
(DEFAULT, "Singrauli", 20),
(DEFAULT, "Tikamgarh", 20),
(DEFAULT, "Ujjain", 20),
(DEFAULT, "Umaria", 20),
(DEFAULT, "Vidisha", 20),

(DEFAULT, "Ahmednagar", 21),
(DEFAULT, "Akola", 21),
(DEFAULT, "Amravati", 21),
(DEFAULT, "Aurangabad", 21),
(DEFAULT, "Beed", 21),
(DEFAULT, "Bhandara", 21),
(DEFAULT, "Buldhana", 21),
(DEFAULT, "Chandrapur", 21),
(DEFAULT, "Dhule", 21),
(DEFAULT, "Gadchiroli", 21),
(DEFAULT, "Gondia", 21),
(DEFAULT, "Hingoli", 21),
(DEFAULT, "Jalgaon", 21),
(DEFAULT, "Jalna", 21),
(DEFAULT, "Kolhapur", 21),
(DEFAULT, "Latur", 21),
(DEFAULT, "Mumbai", 21),
(DEFAULT, "Mumbai Suburban", 21),
(DEFAULT, "Nagpur", 21),
(DEFAULT, "Nanded", 21),
(DEFAULT, "Nandurbar", 21),
(DEFAULT, "Nashik", 21),
(DEFAULT, "Palghar", 21),
(DEFAULT, "Parbhani", 21),
(DEFAULT, "Pune", 21),
(DEFAULT, "Raigad", 21),
(DEFAULT, "Ratnagiri", 21),
(DEFAULT, "Sangli", 21),
(DEFAULT, "Satara", 21),
(DEFAULT, "Sindhudurg", 21),
(DEFAULT, "Solapur", 21),
(DEFAULT, "Thane", 21),
(DEFAULT, "Wardha", 21),
(DEFAULT, "Washim", 21),
(DEFAULT, "Yavatmal", 21),

(DEFAULT, "Bishnupur", 22),
(DEFAULT, "Chandel", 22),
(DEFAULT, "Churachandpur", 22),
(DEFAULT, "Imphal East", 22),
(DEFAULT, "Imphal West", 22),
(DEFAULT, "Jiribam", 22),
(DEFAULT, "Kakching", 22),
(DEFAULT, "Kamjong", 22),
(DEFAULT, "Kangpokpi", 22),
(DEFAULT, "Noney", 22),
(DEFAULT, "Pherzawl", 22),
(DEFAULT, "Senapati", 22),
(DEFAULT, "Tamenglong", 22),
(DEFAULT, "Tengnoupal", 22),
(DEFAULT, "Thoubal", 22),
(DEFAULT, "Ukhrul", 22),

(DEFAULT, "East Garo Hills", 23),
(DEFAULT, "East Jaintia Hills", 23),
(DEFAULT, "East Khasi Hills", 23),
(DEFAULT, "North Garo Hills", 23),
(DEFAULT, "Ribhoi", 23),
(DEFAULT, "South Garo Hills", 23),
(DEFAULT, "South West Garo Hills", 23),
(DEFAULT, "South West Khasi Hills", 23),
(DEFAULT, "West Garo Hills", 23),
(DEFAULT, "West Jaintia Hills", 23),
(DEFAULT, "West Khasi Hills", 23),

(DEFAULT, "Aizwal", 24),
(DEFAULT, "Champhai", 24),
(DEFAULT, "Hnahthial", 24),
(DEFAULT, "Khawzawl", 24),
(DEFAULT, "Kolasib", 24),
(DEFAULT, "Lawngtlai", 24),
(DEFAULT, "Lunglei", 24),
(DEFAULT, "Mamit", 24),
(DEFAULT, "Saiha", 24),
(DEFAULT, "Saitual", 24),
(DEFAULT, "Serchhip", 24),

(DEFAULT, "Dimapur", 25),
(DEFAULT, "Kiphire", 25),
(DEFAULT, "Kohima", 25),
(DEFAULT, "Longleng", 25),
(DEFAULT, "Mokokchung", 25),
(DEFAULT, "Mon", 25),
(DEFAULT, "Peren", 25),
(DEFAULT, "Phek", 25),
(DEFAULT, "Tuensang", 25),
(DEFAULT, "Wokha", 25),
(DEFAULT, "Zunheboto", 25),

(DEFAULT, "Angul", 26),
(DEFAULT, "Balangir", 26),
(DEFAULT, "Balasore", 26),
(DEFAULT, "Bargarh", 26),
(DEFAULT, "Bhadrak", 26),
(DEFAULT, "Boudh", 26),
(DEFAULT, "Cuttack", 26),
(DEFAULT, "Deogarh", 26),
(DEFAULT, "Dhenkanal", 26),
(DEFAULT, "Gajapati", 26),
(DEFAULT, "Ganjam", 26),
(DEFAULT, "Jagatsinghpur", 26),
(DEFAULT, "Jajpur", 26),
(DEFAULT, "Jharsuguda", 26),
(DEFAULT, "Kalahandi", 26),
(DEFAULT, "Kandhamal", 26),
(DEFAULT, "Kendrapara", 26),
(DEFAULT, "Kendujhar", 26),
(DEFAULT, "Khordha", 26),
(DEFAULT, "Koraput", 26),
(DEFAULT, "Malkangiri", 26),
(DEFAULT, "Mayurbhanj", 26),
(DEFAULT, "Nabarangapur", 26),
(DEFAULT, "Nayagarh", 26),
(DEFAULT, "Nuapada", 26),
(DEFAULT, "Puri", 26),
(DEFAULT, "Rayagada", 26),
(DEFAULT, "Sambalpur", 26),
(DEFAULT, "Subarnapur", 26),
(DEFAULT, "Sundargarh", 26),

(DEFAULT, "Karaikal", 27),
(DEFAULT, "Mahe", 27),
(DEFAULT, "Puducherry", 27),
(DEFAULT, "Yanam", 27),

(DEFAULT, "Amritsar", 28),
(DEFAULT, "Barnala", 28),
(DEFAULT, "Bathinda", 28),
(DEFAULT, "Faridkot", 28),
(DEFAULT, "Fatehgarh Sahib", 28),
(DEFAULT, "Fazilka", 28),
(DEFAULT, "Ferozepur", 28),
(DEFAULT, "Gurdaspur", 28),
(DEFAULT, "Hoshiarpur", 28),
(DEFAULT, "Jalandhar", 28),
(DEFAULT, "Kapurthala", 28),
(DEFAULT, "Ludhiana", 28),
(DEFAULT, "Mansa", 28),
(DEFAULT, "Moga", 28),
(DEFAULT, "Pathankot", 28),
(DEFAULT, "Patiala", 28),
(DEFAULT, "Rupnagar", 28),
(DEFAULT, "S.A.S. Nagar", 28),
(DEFAULT, "Sangrur", 28),
(DEFAULT, "Shahid Bhagat Singh Nagar", 28),
(DEFAULT, "Sri Muktsar Sahib", 28),
(DEFAULT, "Tarn Taran", 28),

(DEFAULT, "Ajmer", 29),
(DEFAULT, "Alwar", 29),
(DEFAULT, "Banswara", 29),
(DEFAULT, "Baran", 29),
(DEFAULT, "Barmer", 29),
(DEFAULT, "Bharatpur", 29),
(DEFAULT, "Bhilwara", 29),
(DEFAULT, "Bikaner", 29),
(DEFAULT, "Bundi", 29),
(DEFAULT, "Chittorgarh", 29),
(DEFAULT, "Churu", 29),
(DEFAULT, "Dausa", 29),
(DEFAULT, "Dholpur", 29),
(DEFAULT, "Dungarpur", 29),
(DEFAULT, "Ganganagar", 29),
(DEFAULT, "Hanumangarh", 29),
(DEFAULT, "Jaipur", 29),
(DEFAULT, "Jaisalmer", 29),
(DEFAULT, "Jalore", 29),
(DEFAULT, "Jhalawar", 29),
(DEFAULT, "Jhunjhunu", 29),
(DEFAULT, "Jodhpur", 29),
(DEFAULT, "Karauli", 29),
(DEFAULT, "Kota", 29),
(DEFAULT, "Nagaur", 29),
(DEFAULT, "Pali", 29),
(DEFAULT, "Pratapgarh", 29),
(DEFAULT, "Rajsamand", 29),
(DEFAULT, "Sawai Madhopur", 29),
(DEFAULT, "Sikar", 29),
(DEFAULT, "Sirohi", 29),
(DEFAULT, "Tonk", 29),
(DEFAULT, "Udaipur", 29),

(DEFAULT, "East Sikkim", 30),
(DEFAULT, "North Sikkim", 30),
(DEFAULT, "South Sikkim", 30),
(DEFAULT, "West Sikkim", 30),

(DEFAULT, "Ariyalur", 31),
(DEFAULT, "Chengalpattu", 31),
(DEFAULT, "Chennai", 31),
(DEFAULT, "Coimbatore", 31),
(DEFAULT, "Cuddalore", 31),
(DEFAULT, "Dharmapuri", 31),
(DEFAULT, "Dindigul", 31),
(DEFAULT, "Erode", 31),
(DEFAULT, "Kallakurichi", 31),
(DEFAULT, "Kancheepuram", 31),
(DEFAULT, "Kanyakumari", 31),
(DEFAULT, "Karur", 31),
(DEFAULT, "Krishnagiri", 31),
(DEFAULT, "Madurai", 31),
(DEFAULT, "Nagapattinam", 31),
(DEFAULT, "Namakkal", 31),
(DEFAULT, "Nilgiris", 31),
(DEFAULT, "Perambalur", 31),
(DEFAULT, "Pudukkottai", 31),
(DEFAULT, "Ramanathapuram", 31),
(DEFAULT, "Ranipet", 31),
(DEFAULT, "Salem", 31),
(DEFAULT, "Sivaganga", 31),
(DEFAULT, "Tenkasi", 31),
(DEFAULT, "Thanjavur", 31),
(DEFAULT, "Theni", 31),
(DEFAULT, "Thiruvallur", 31),
(DEFAULT, "Thiruvarur", 31),
(DEFAULT, "Thoothukkudi", 31),
(DEFAULT, "Tiruchirappalli", 31),
(DEFAULT, "Tirunelveli", 31),
(DEFAULT, "Tirupathur", 31),
(DEFAULT, "Tiruppur", 31),
(DEFAULT, "Tiruvannamalai", 31),
(DEFAULT, "Vellore", 31),
(DEFAULT, "Viluppuram", 31),
(DEFAULT, "Virudhunagar", 31),

(DEFAULT, "Adilabad", 32),
(DEFAULT, "Bhadradri Kothagudem", 32),
(DEFAULT, "Hyderabad", 32),
(DEFAULT, "Jagtial", 32),
(DEFAULT, "Jangaon", 32),
(DEFAULT, "Jayashankar Bhupalapally", 32),
(DEFAULT, "Jogulamba Gadwal", 32),
(DEFAULT, "Kamareddy", 32),
(DEFAULT, "Karimnagar", 32),
(DEFAULT, "Khammam", 32),
(DEFAULT, "Komaram Bheem", 32),
(DEFAULT, "Mahabubabad", 32),
(DEFAULT, "Mahabubnagar", 32),
(DEFAULT, "Mancherial", 32),
(DEFAULT, "Medak", 32),
(DEFAULT, "Medchal Malkajgiri", 32),
(DEFAULT, "Mulugu", 32),
(DEFAULT, "Nagarkurnool", 32),
(DEFAULT, "Nalgonda", 32),
(DEFAULT, "Narayanpet", 32),
(DEFAULT, "Nirmal", 32),
(DEFAULT, "Nizamabad", 32),
(DEFAULT, "Peddapalli", 32),
(DEFAULT, "Rajanna Sircilla", 32),
(DEFAULT, "Ranga Reddy", 32),
(DEFAULT, "Sangareddy", 32),
(DEFAULT, "Siddipet", 32),
(DEFAULT, "Suryapet", 32),
(DEFAULT, "Vikarabad", 32),
(DEFAULT, "Wanaparthy", 32),
(DEFAULT, "Warangal Rural", 32),
(DEFAULT, "Warangal Urban", 32),
(DEFAULT, "Yadadri Bhuvanagiri", 32),

(DEFAULT, "Dhalai", 33),
(DEFAULT, "Gomati", 33),
(DEFAULT, "Khowai", 33),
(DEFAULT, "North Tripura", 33),
(DEFAULT, "Sipahijala", 33),
(DEFAULT, "South Tripura", 33),
(DEFAULT, "Unokoti", 33),
(DEFAULT, "West Tripura", 33),

(DEFAULT, "Agra", 34),
(DEFAULT, "Aligarh", 34),
(DEFAULT, "Ambedkar Nagar", 34),
(DEFAULT, "Amethi", 34),
(DEFAULT, "Amroha", 34),
(DEFAULT, "Auraiya", 34),
(DEFAULT, "Ayodhya", 34),
(DEFAULT, "Azamgarh", 34),
(DEFAULT, "Baghpat", 34),
(DEFAULT, "Bahraich", 34),
(DEFAULT, "Ballia", 34),
(DEFAULT, "Balrampur", 34),
(DEFAULT, "Banda", 34),
(DEFAULT, "Barabanki", 34),
(DEFAULT, "Bareilly", 34),
(DEFAULT, "Basti", 34),
(DEFAULT, "Bhadohi", 34),
(DEFAULT, "Bijnor", 34),
(DEFAULT, "Budaun", 34),
(DEFAULT, "Bulandshahr", 34),
(DEFAULT, "Chandauli", 34),
(DEFAULT, "Chitrakoot", 34),
(DEFAULT, "Deoria", 34),
(DEFAULT, "Etah", 34),
(DEFAULT, "Etawah", 34),
(DEFAULT, "Farrukhabad", 34),
(DEFAULT, "Fatehpur", 34),
(DEFAULT, "Firozabad", 34),
(DEFAULT, "Gautam Buddha Nagar", 34),
(DEFAULT, "Ghaziabad", 34),
(DEFAULT, "Ghazipur", 34),
(DEFAULT, "Gonda", 34),
(DEFAULT, "Gorakhpur", 34),
(DEFAULT, "Hamirpur", 34),
(DEFAULT, "Hapur", 34),
(DEFAULT, "Hardoi", 34),
(DEFAULT, "Hathras", 34),
(DEFAULT, "Jalaun", 34),
(DEFAULT, "Jaunpur", 34),
(DEFAULT, "Jhansi", 34),
(DEFAULT, "Kannauj", 34),
(DEFAULT, "Kanpur Dehat", 34),
(DEFAULT, "Kanpur Nagar", 34),
(DEFAULT, "Kasganj", 34),
(DEFAULT, "Kaushambi", 34),
(DEFAULT, "Kushinagar", 34),
(DEFAULT, "Lakhimpur Kheri", 34),
(DEFAULT, "Lalitpur", 34),
(DEFAULT, "Lucknow", 34),
(DEFAULT, "Maharajganj", 34),
(DEFAULT, "Mahoba", 34),
(DEFAULT, "Mainpuri", 34),
(DEFAULT, "Mathura", 34),
(DEFAULT, "Mau", 34),
(DEFAULT, "Meerut", 34),
(DEFAULT, "Mirzapur", 34),
(DEFAULT, "Moradabad", 34),
(DEFAULT, "Muzaffarnagar", 34),
(DEFAULT, "Pilibhit", 34),
(DEFAULT, "Pratapgarh", 34),
(DEFAULT, "Prayagraj", 34),
(DEFAULT, "Rae Bareli", 34),
(DEFAULT, "Rampur", 34),
(DEFAULT, "Saharanpur", 34),
(DEFAULT, "Sambhal", 34),
(DEFAULT, "Sant Kabir Nagar", 34),
(DEFAULT, "Shahjahanpur", 34),
(DEFAULT, "Shamli", 34),
(DEFAULT, "Shrawasti", 34),
(DEFAULT, "Siddharthnagar", 34),
(DEFAULT, "Sitapur", 34),
(DEFAULT, "Sonbhadra", 34),
(DEFAULT, "Sultanpur", 34),
(DEFAULT, "Unnao", 34),
(DEFAULT, "Varanasi", 34),

(DEFAULT, "Almora", 35),
(DEFAULT, "Bageshwar", 35),
(DEFAULT, "Chamoli", 35),
(DEFAULT, "Champawat", 35),
(DEFAULT, "Dehradun", 35),
(DEFAULT, "Haridwar", 35),
(DEFAULT, "Nainital", 35),
(DEFAULT, "Pauri Garhwal", 35),
(DEFAULT, "Pithoragarh", 35),
(DEFAULT, "Rudraprayag", 35),
(DEFAULT, "Tehri Garhwal", 35),
(DEFAULT, "Udham Singh Nagar", 35),
(DEFAULT, "Uttarkashi", 35),

(DEFAULT, "Alipurduar", 36),
(DEFAULT, "Bankura", 36),
(DEFAULT, "Birbhum", 36),
(DEFAULT, "Cooch Behar", 36),
(DEFAULT, "Dakshin Dinajpur", 36),
(DEFAULT, "Darjeeling", 36),
(DEFAULT, "Hooghly", 36),
(DEFAULT, "Howrah", 36),
(DEFAULT, "Jalpaiguri", 36),
(DEFAULT, "Jhargram", 36),
(DEFAULT, "Kalimpong", 36),
(DEFAULT, "Kolkata", 36),
(DEFAULT, "Malda", 36),
(DEFAULT, "Murshidabad", 36),
(DEFAULT, "Nadia", 36),
(DEFAULT, "North 24 Parganas", 36),
(DEFAULT, "Paschim Bardhaman", 36),
(DEFAULT, "Paschim Medinipur", 36),
(DEFAULT, "Purba Bardhaman", 36),
(DEFAULT, "Purba Medinipur", 36),
(DEFAULT, "Purulia", 36),
(DEFAULT, "South 24 Parganas", 36),
(DEFAULT, "Uttar Dinajpur", 36);


INSERT INTO role VALUES
(DEFAULT, "ADMIN"),
(DEFAULT, "DISTRICT"),
(DEFAULT, "CENTRE"),
(DEFAULT, "BENEFICIARY");

INSERT INTO user VALUES(DEFAULT, "admin@admin", "$2y$12$0ySlGPA/.V/YiG7Ad2.7DeMBYwWsDZi9zvn0A4PKtMZwjePrH0e2O","admin");

INSERT INTO user_roles VALUES(1, 1);
